version: "3.8"

services:
  mysql:
    user: '1000:50'
    image: mysql:5.7
    restart: always
    environment:
      - 'MYSQL_PASSWORD=${MYSQL_PASS}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}'
      - 'MYSQL_DATABASE=${MYSQL_DB}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/create-db.sql
volumes:
  mysql_data:
    driver: local
