name: Huddle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node
      	uses: actions/setup-node@v2
      	with: 
          node-version: "16.x"
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build Frontend
	run: |
          cd ./backend
          npm run build
      - name: Cache Maven packages
	working-directory: ./backend
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Package with Maven
        run: |
          cd ./backend
          mvn package -Dmaven.test.skip  
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Build the Docker image
        run: |
          cd ./backend
          docker build . --file Dockerfile --tag sohamp1228/huddle:$(date +%s)
      - name: Docker Push
        run: |
          cd ./backend
          docker push sohamp1228/huddle

