name: Huddle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Frontend
        run: |
          cd ./frontend
          rm -rf node_modules/
          npm ci
          npm run build
      - name: Cache Maven 
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Package with Maven
        run: |
          cd ./backend
          mvn package -Dmaven.test.skip  
      - name: Generate Docker Tag Based on Timestamp
        run: echo TAG=$(date +%s) >> $GITHUB_ENV
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          TAG: ${{env.TAG}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Build the Docker image
        run: |
          cd ./backend
          docker build . --file Dockerfile -t sohamp1228/huddle:latest -t sohamp1228/huddle:$TAG
      - name: Docker Push
        run: |
          cd ./backend
          docker push --all-tags sohamp1228/huddle
      - name: Connect to Digital Ocean and Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.DO_HOST }}
            username: ${{ secrets.DO_USERNAME }}
            key: ${{ secrets.DO_KEY }}
            passphrase: ${{secrets.DO_PASSPHRASE}}
            script: |
              cd /huddle/docker
              docker-compose pull huddle
              docker-compose up --detach --build huddle
              docker image prune -a -f
